name: Update Events JSON

on:
  push:
    paths:
      - 'data/*.json'
    branches:
      - main

jobs:
  process-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate and process new JSON files
        run: |
          EVENT_FILE="data/events.json"
          NEW_FILES=$(find data -type f -name "*.json" ! -name "events.json")

          TEMP_FILE="temp_events.json"
          echo "[" > "$TEMP_FILE"

          validate_json() {
            FILE=$1
            jq -e '
              .eventName and
              .eventDescription and
              (.eventDate | test("^[0-9]{4}-[0-9]{2}-[0-9]{2}$")) and
              (.eventTime | test("^[0-9]{2}:[0-9]{2}$")) and
              .eventVenue and
              (.eventLink | test("^https?://")) and
              .location and
              .communityName and
              (.communityLogo | test("^https?://"))
            ' "$FILE" > /dev/null 2>&1
          }

          for FILE in $NEW_FILES; do
            echo "Processing $FILE..."
            if validate_json "$FILE"; then
              echo "Valid file: $FILE"
              cat "$FILE" >> "$TEMP_FILE"
              echo "," >> "$TEMP_FILE" 
              rm -f "$FILE"
            else
              echo "Invalid file: $FILE. Skipping."
            fi
          done

          sed -i '$ s/,$//' "$TEMP_FILE"
          echo "]" >> "$TEMP_FILE"

          # Merge the valid data into events.json
          jq -s '.[0] + .[1]' "$EVENT_FILE" "$TEMP_FILE" > merged.json && mv merged.json "$EVENT_FILE"
          rm -f "$TEMP_FILE"

          echo "Updated events.json:"
          cat "$EVENT_FILE"

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add data/events.json
          git commit -m "Update events.json with validated data"
          git push
